spring.application.name=module-administration
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raas_platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=mfOs6TXYEUOTWkceeDYkFB2NllRI8kuhz992qdd2fv1wSUarlUokme+7htVhp0AQTU21wNeIWnrV5JAkf2SUtQ==
jwt.access-token-expiration=9000000
jwt.refresh-token-expiration=604800000

logging.level.org.springframework=DEBUG

# LIQUIDBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# ??? REDIS ??????????????????????????????????????????????
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# ??? OTP ????????????????????????????????????????????????
otp.expiration-minutes=5
otp.length=6

# ??? GMAIL SMTP ?????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bentitatahaamine2@gmail.com
spring.mail.password=flmgxwxrgwylyfri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ??? RECAPTCHA ???????????????????????????????????????????
recaptcha.secret-key=6LeLAIcsAAAAACW1uJCF-LJ99QW1hsst7pTXoM_P
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
recaptcha.min-score=0.5
recaptcha.enabled=false

