spring.application.name=module-administration

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raas_platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT (set as env var in real deployments)
jwt.secret=CHANGE_ME
jwt.access-token-expiration=9000000
jwt.refresh-token-expiration=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# OTP
otp.expiration-minutes=5
otp.length=6

# Mail (set as env vars in real deployments)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=CHANGE_ME
spring.mail.password=CHANGE_ME

# reCAPTCHA (optional)
recaptcha.secret-key=CHANGE_ME
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
recaptcha.min-score=0.5
recaptcha.enabled=false

