spring.application.name=module-administration
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raas_platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=K8f3pT9zQ1wL6yB2vE4nR7cH0sU5xA3dF8gJ2kL9mP1
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

logging.level.org.springframework=DEBUG