package talan.pfe.rulengine.controllers;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import talan.pfe.rulengine.dtos.request.InsightStatusUpdateRequest;
import talan.pfe.rulengine.dtos.response.AiInsightResponse;
import talan.pfe.rulengine.entites.AiInsight;
import talan.pfe.rulengine.entites.User;
import talan.pfe.rulengine.enums.AgentType;
import talan.pfe.rulengine.enums.InsightStatus;
import talan.pfe.rulengine.exception.BadRequestException;
import talan.pfe.rulengine.exception.ResourceNotFoundException;
import talan.pfe.rulengine.repositories.AiInsightRepository;
import talan.pfe.rulengine.security.CurrentUserResolver;

import java.util.List;

@RestController
@RequestMapping("/api/anomalies")
@RequiredArgsConstructor
@Tag(name = "Anomaly Detection", description = "Insights generated by the Anomaly Detection Agent")
public class AnomalyDetectionController {

    private final AiInsightRepository aiInsightRepository;
    private final CurrentUserResolver currentUserResolver;

    @GetMapping
    @PreAuthorize("hasAnyRole('GLOBAL_ADMIN', 'ADMIN', 'MANAGER', 'VIEWER')")
    @Operation(summary = "List all anomaly detection insights for the current tenant")
    public ResponseEntity<List<AiInsightResponse>> getAnomalies() {
        var user = currentUserResolver.requireUser();
        if (user.getTenant() == null) {
            throw new BadRequestException("Tenant context is required.");
        }
        List<AiInsightResponse> result = aiInsightRepository
                .findByTenantIdAndAgentTypeOrderByGeneratedAtDesc(
                        user.getTenant().getId(), AgentType.ANOMALY_DETECTION_AGENT)
                .stream()
                .map(this::toResponse)
                .toList();
        return ResponseEntity.ok(result);
    }

    @GetMapping("/latest")
    @PreAuthorize("hasAnyRole('GLOBAL_ADMIN', 'ADMIN', 'MANAGER', 'VIEWER')")
    @Operation(summary = "Get the latest anomaly detection insight for the current tenant")
    public ResponseEntity<AiInsightResponse> latestAnomaly() {
        var user = currentUserResolver.requireUser();
        if (user.getTenant() == null) {
            throw new BadRequestException("Tenant context is required.");
        }
        AiInsight insight = aiInsightRepository
                .findFirstByTenantIdAndAgentTypeOrderByGeneratedAtDesc(
                        user.getTenant().getId(), AgentType.ANOMALY_DETECTION_AGENT)
                .orElseThrow(() -> new ResourceNotFoundException("Aucune anomalie détectée pour ce tenant."));
        return ResponseEntity.ok(toResponse(insight));
    }

    @PatchMapping("/{id}/status")
    @PreAuthorize("hasAnyRole('GLOBAL_ADMIN', 'ADMIN')")
    @Operation(summary = "Accept or reject an anomaly insight")
    public ResponseEntity<AiInsightResponse> updateStatus(
            @PathVariable Long id,
            @Valid @RequestBody InsightStatusUpdateRequest request) {
        User user = currentUserResolver.requireUser();
        if (user.getTenant() == null) {
            throw new BadRequestException("Tenant context is required.");
        }

        AiInsight insight = aiInsightRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Anomalie introuvable."));
        if (!insight.getTenant().getId().equals(user.getTenant().getId())) {
            throw new ResourceNotFoundException("Anomalie introuvable.");
        }

        InsightStatus next;
        try {
            next = InsightStatus.valueOf(request.getStatus().toUpperCase());
        } catch (Exception e) {
            throw new BadRequestException("Seuls ACCEPTED ou REJECTED sont autorisés.");
        }

        if (next == InsightStatus.ACCEPTED) {
            insight.accept(user);
        } else if (next == InsightStatus.REJECTED) {
            insight.reject(user);
        } else {
            throw new BadRequestException("Seuls ACCEPTED ou REJECTED sont autorisés.");
        }

        return ResponseEntity.ok(toResponse(aiInsightRepository.save(insight)));
    }

    private AiInsightResponse toResponse(AiInsight e) {
        return AiInsightResponse.builder()
                .id(e.getId())
                .ruleSetId(e.getRuleSet() != null ? e.getRuleSet().getId() : null)
                .title(e.getTitle())
                .description(e.getDescription())
                .suggestion(e.getSuggestion())
                .status(e.getStatus())
                .type(e.getType())
                .agentType(e.getAgentType())
                .confidence(e.getConfidence())
                .generatedAt(e.getGeneratedAt())
                .resolvedAt(e.getResolvedAt())
                .build();
    }
}
