package talan.pfe.rulengine.controllers;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import talan.pfe.rulengine.dtos.response.AiInsightResponse;
import talan.pfe.rulengine.entites.AiInsight;
import talan.pfe.rulengine.enums.AgentType;
import talan.pfe.rulengine.exception.BadRequestException;
import talan.pfe.rulengine.repositories.AiInsightRepository;
import talan.pfe.rulengine.security.CurrentUserResolver;

import java.util.List;

@RestController
@RequestMapping("/api/external-analysis")
@RequiredArgsConstructor
@Tag(name = "External Analysis", description = "Insights generated by the External Analysis Agent")
public class ExternalAnalysisController {

    private final AiInsightRepository aiInsightRepository;
    private final CurrentUserResolver currentUserResolver;

    @GetMapping("/insights")
    @PreAuthorize("hasAnyRole('GLOBAL_ADMIN', 'ADMIN', 'MANAGER', 'VIEWER')")
    @Operation(summary = "List all external analysis insights for the current tenant")
    public ResponseEntity<List<AiInsightResponse>> getInsights() {
        var user = currentUserResolver.requireUser();
        if (user.getTenant() == null) {
            throw new BadRequestException("Tenant context is required.");
        }
        List<AiInsightResponse> result = aiInsightRepository
                .findByTenantIdAndAgentTypeOrderByGeneratedAtDesc(
                        user.getTenant().getId(), AgentType.EXTERNAL_ANALYSIS_AGENT)
                .stream()
                .map(this::toResponse)
                .toList();
        return ResponseEntity.ok(result);
    }

    private AiInsightResponse toResponse(AiInsight e) {
        return AiInsightResponse.builder()
                .id(e.getId())
                .ruleSetId(e.getRuleSet() != null ? e.getRuleSet().getId() : null)
                .title(e.getTitle())
                .description(e.getDescription())
                .suggestion(e.getSuggestion())
                .status(e.getStatus())
                .type(e.getType())
                .agentType(e.getAgentType())
                .confidence(e.getConfidence())
                .generatedAt(e.getGeneratedAt())
                .resolvedAt(e.getResolvedAt())
                .build();
    }
}
