package talan.pfe.rulengine.enums;

public enum AuditAction {
    // Tenant
    TENANT_CREATED,
    TENANT_UPDATED,
    TENANT_ACTIVATED,
    TENANT_DEACTIVATED,
    TENANT_DELETED,

    // User
    USER_CREATED,
    USER_UPDATED,
    USER_ROLE_CHANGED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_DELETED,

    // ApiKey
    APIKEY_CREATED,
    APIKEY_REVOKED,
    APIKEY_REGENERATED,
    APIKEY_DELETED,

    // RuleSet
    RULESET_CREATED,
    RULESET_UPDATED,
    RULESET_ACTIVATED,
    RULESET_ARCHIVED,
    RULESET_UNARCHIVED,
    RULESET_MOVED_TO_DRAFT,
    RULESET_DELETED,

    // Rule
    RULE_CREATED,
    RULE_UPDATED,
    RULE_ENABLED,
    RULE_DISABLED,
    RULE_DELETED,

    // Conditions & Actions
    CONDITION_CREATED,
    CONDITION_UPDATED,
    CONDITION_DELETED,
    ACTION_CREATED,
    ACTION_UPDATED,
    ACTION_DELETED,

    // Versioning
    VERSION_CREATED,
    ROLLBACK_PERFORMED,

    // Import/Export
    CONFIG_IMPORTED,
    CONFIG_EXPORTED,

    // Evaluation
    RULESET_EVALUATED,

    // AI
    INSIGHT_ACCEPTED,
    INSIGHT_REJECTED
}